<?php
// WARNING : DO NOT EDIT THIS FILE, IT IS GENERATED AUTOMATICALLY !
// You can add your customisations in the "diogenes.debian.inc.php" file

// locations
$globals->spoolroot = "/var/spool/diogenes";
$globals->rcsroot = "/var/lib/diogenes";
$globals->root = "/usr/share/diogenes";
$globals->libroot = "/usr/share/php/diogenes";

// database access
$globals->dbdb = "@dbname@";
$globals->dbhost = "@dbserver@";
$globals->dbuser = "@dbuser@";
$globals->dbpwd = "@dbpass@";

// include local configuration
require("diogenes.debian.inc.php");

?>
